direction: down

title: |md
  # Document Structure
|

title -> *: {style.opacity: 0}

Math.Differential Geometry -> Physics

Math: {
  Differential Geometry
  Monte Carlo Estimator
  MIS: Multi-Importance Sampler
}

Physics: {
  Energy -> Flux -> Radiance -> Irradiance
  Radiance -> Luminance
  Energy -> Frensel Equation

  Energy
  Flux
  Radiance
  Irradiance
  Luminance

  Snell's Law
  Frensel Equation
}
